In [2]:
import pandas as pd
import numpy as np

In [3]:
#create sample messy employee data
data = {
    "EmpId": [101, 102, "103", 104, 105, 106, 107, 108, 109, 110],
    "fullName": [
        "  Alice Johnson  ", "MICHEAL smith", "sarah lee", "David-Kim", None, "john brown",
        "Emma Wilson", "TOM  davis", "Jane Miller", "Chris taylor"
    ], 
     "Dept": ["IT", "hr", "Mktng", "IT", "Customer Care", "marketing", "Finance", None, "HR", "marketing"],
    "Age": [29, "thirty-five", 26, 31, 42, 27, 33, 30, None, 28],
    "Salary($)": ["$5500.50", "4800", "4200.75", "NaN", "6100", "4,300", "5800", "5000", "4700.0", "4400"],
    "JoinDate": [
        "2021/04/12", "2020/11/01", "2022/01/18", "2019/9/25", "2018/07/05", 
        "2021/10/14", "2019/12/01", "2020/03/22", "2021/05/10", "2022/02/05"
    ],
    "Performance": [87, "73", 90, 65, 82, 75, 88, None, "79%", "91"],
    "Remote?": ["Yes", "No", "Y", "N", "yes", "no", "Y", "Yes", None, "True"]
}

In [4]:
df = pd.DataFrame(data)

df.to_csv("employee_dataset.csv", index=False)

df = pd.read_csv("employee_dataset.csv")

df

,EmpId,fullName,Dept,Age,Salary($),JoinDate,Performance,Remote?
0,101,Alice Johnson,IT,29,$5500.50,2021/04/12,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020/11/01,73,No
2,103,sarah lee,Mktng,26,4200.75,2022/01/18,90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,2018/07/05,82,yes
5,106,john brown,marketing,27,"4,300",2021/10/14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,TOM davis,NaN,30,5000,2020/03/22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.0,2021/05/10,79%,NaN
9,110,Chris taylor,marketing,28,4400,2022/02/05,91,True

In [5]:
#get the dataframe shapes
df.shape

(10, 8)

In [6]:
#get the information of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmpId        10 non-null     int64
 1   fullName     9 non-null      object
 2   Dept         9 non-null      object
 3   Age          9 non-null      object
 4   Salary($)    9 non-null      object
 5   JoinDate     10 non-null     object
 6   Performance  9 non-null      object
 7   Remote?      9 non-null      object
dtypes: int64(1), object(7)
memory usage: 768.0+ bytes

In [7]:
#get first five rows of the dataset
df.head()

,EmpId,fullName,Dept,Age,Salary($),JoinDate,Performance,Remote?
0,101,Alice Johnson,IT,29,$5500.50,2021/04/12,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020/11/01,73,No
2,103,sarah lee,Mktng,26,4200.75,2022/01/18,90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,2018/07/05,82,yes

In [8]:
#get columns for the dataset
df.columns

Index(['EmpId', 'fullName', 'Dept', 'Age', 'Salary($)', 'JoinDate',
       'Performance', 'Remote?'],
      dtype='object')

In [9]:
#get missing values
df.isnull().sum()

EmpId          0
fullName       1
Dept           1
Age            1
Salary($)      1
JoinDate       0
Performance    1
Remote?        1
dtype: int64

In [10]:
#get uniqueness of the dataset
print(df["Dept"].unique())
print(df['Age'].unique())
print(df['Remote?'].unique())

['IT' 'hr' 'Mktng' 'Customer Care' 'marketing' 'Finance' nan 'HR']
['29' 'thirty-five' '26' '31' '42' '27' '33' '30' nan '28']
['Yes' 'No' 'Y' 'N' 'yes' 'no' nan 'True']

In [11]:
#access series data
df["Salary($)"].tolist()

['$5500.50',
 '4800',
 '4200.75',
 nan,
 '6100',
 '4,300',
 '5800',
 '5000',
 '4700.0',
 '4400']

In [12]:
df['fullName'].tolist()

['  Alice Johnson  ',
 'MICHEAL smith',
 'sarah lee',
 'David-Kim',
 nan,
 'john brown',
 'Emma Wilson',
 'TOM  davis',
 'Jane Miller',
 'Chris taylor']

In [13]:
df['Salary($)'].head()

0    $5500.50
1        4800
2     4200.75
3         NaN
4        6100
Name: Salary($), dtype: object

In [14]:
#start cleaning inconsistence valus
#rename inconsistence columns
df.rename(columns={
    'EmpId': 'emp_id',
    'fullName': 'full_name',
    'Dept': 'department',
    'Age': 'age',
    'Salary($)': 'salary',
    'JoinDate': 'join_date',
    'Performance': 'performance',
    'Remote?': 'remote'
}, inplace=True)

df

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29,$5500.50,2021/04/12,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020/11/01,73,No
2,103,sarah lee,Mktng,26,4200.75,2022/01/18,90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,2018/07/05,82,yes
5,106,john brown,marketing,27,"4,300",2021/10/14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,TOM davis,NaN,30,5000,2020/03/22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.0,2021/05/10,79%,NaN
9,110,Chris taylor,marketing,28,4400,2022/02/05,91,True

In [15]:
df['full_name'] = df['full_name'].str.strip()
df['full_name'] = df['full_name'].str.title()
df['full_name'] = df['full_name'].str.replace(r"\s+", " ", regex=True)
df['full_name'] = df['full_name'].str.replace(r"-", " ")
df['full_name'].tolist()

['Alice Johnson',
 'Micheal Smith',
 'Sarah Lee',
 'David Kim',
 nan,
 'John Brown',
 'Emma Wilson',
 'Tom Davis',
 'Jane Miller',
 'Chris Taylor']

In [16]:
#clean inconsistent values on department
df["department"].replace({
    "hr": "HR",
    "Mktng": "Marketing",
    "marketing": "Marketing"
}, inplace=True)

df

C:\Users\ola-dev\AppData\Local\Temp\ipykernel_6112\4184915569.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["department"].replace({

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29,$5500.50,2021/04/12,87,Yes
1,102,Micheal Smith,HR,thirty-five,4800,2020/11/01,73,No
2,103,Sarah Lee,Marketing,26,4200.75,2022/01/18,90,Y
3,104,David Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,2018/07/05,82,yes
5,106,John Brown,Marketing,27,"4,300",2021/10/14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,Tom Davis,NaN,30,5000,2020/03/22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.0,2021/05/10,79%,NaN
9,110,Chris Taylor,Marketing,28,4400,2022/02/05,91,True

In [17]:
#clean inconsistent values on age
def clean_age(value):
    if value == "thirty-five":
        return 35
    elif isinstance(value, (int, float)):
        return value
    elif isinstance(value, str) and value.isdigit():
        return int(value)
    else:
        return np.nan

df['age'] = df['age'].apply(clean_age)

df['age']

0    29.0
1    35.0
2    26.0
3    31.0
4    42.0
5    27.0
6    33.0
7    30.0
8     NaN
9    28.0
Name: age, dtype: float64

In [18]:
#clean inconsistent value on salary
df["salary"] = (
    df["salary"]
    .astype(str)
    .replace(r"[$,]", "", regex=True)
    .replace("NAN", np.nan)
    .astype(float)
)

df["salary"]

0    5500.50
1    4800.00
2    4200.75
3        NaN
4    6100.00
5    4300.00
6    5800.00
7    5000.00
8    4700.00
9    4400.00
Name: salary, dtype: float64

In [19]:
df['join_date'] = pd.to_datetime(df['join_date'], errors='coerce')
df['join_date']

0   2021-04-12
1   2020-11-01
2   2022-01-18
3   2019-09-25
4   2018-07-05
5   2021-10-14
6   2019-12-01
7   2020-03-22
8   2021-05-10
9   2022-02-05
Name: join_date, dtype: datetime64[ns]

In [20]:
#clean inconsistent value in performance
df['performance'] = (
    df['performance']
    .astype(str)
    .str.replace('%', '', regex=False)
    .replace("None", np.nan)
    .astype(float)
)

df['performance']

0    87.0
1    73.0
2    90.0
3    65.0
4    82.0
5    75.0
6    88.0
7     NaN
8    79.0
9    91.0
Name: performance, dtype: float64

In [21]:
#clean inconsistent value on remote
df['remote'].replace({
    'Y': 'Yes',
    'N': 'No',
    'yes': 'Yes',
    'no': 'No',
    'True': 'Yes',
    None: np.nan
}, inplace=True)

df['remote']

C:\Users\ola-dev\AppData\Local\Temp\ipykernel_6112\481794493.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['remote'].replace({

0    Yes
1     No
2    Yes
3     No
4    Yes
5     No
6    Yes
7    Yes
8    NaN
9    Yes
Name: remote, dtype: object

In [22]:
#clean inconsistent empid value
df["emp_id"] = pd.to_numeric(df["emp_id"], errors='coerce')
df['emp_id']

0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
8    109
9    110
Name: emp_id, dtype: int64

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   emp_id       10 non-null     int64
 1   full_name    9 non-null      object
 2   department   9 non-null      object
 3   age          9 non-null      float64
 4   salary       9 non-null      float64
 5   join_date    10 non-null     datetime64[ns]
 6   performance  9 non-null      float64
 7   remote       9 non-null      object
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 768.0+ bytes

In [24]:
#handling missing value
df['full_name'] = df['full_name'].fillna("Unknown")
df['full_name']

0    Alice Johnson
1    Micheal Smith
2        Sarah Lee
3        David Kim
4          Unknown
5       John Brown
6      Emma Wilson
7        Tom Davis
8      Jane Miller
9     Chris Taylor
Name: full_name, dtype: object

In [25]:
df['department'] = df['department'].fillna(df['department'].mode()[0])
df['department']

0               IT
1               HR
2        Marketing
3               IT
4    Customer Care
5        Marketing
6          Finance
7        Marketing
8               HR
9        Marketing
Name: department, dtype: object

In [26]:
df['age'] = df['age'].fillna(df['age'].median())
df['age']

0    29.0
1    35.0
2    26.0
3    31.0
4    42.0
5    27.0
6    33.0
7    30.0
8    30.0
9    28.0
Name: age, dtype: float64

In [27]:
df['salary'] = df['salary'].fillna(df['salary'].median())
df['salary']

0    5500.50
1    4800.00
2    4200.75
3    4800.00
4    6100.00
5    4300.00
6    5800.00
7    5000.00
8    4700.00
9    4400.00
Name: salary, dtype: float64

In [28]:
df['performance'] = df['performance'].fillna(df['performance'].median())
df['performance']

0    87.0
1    73.0
2    90.0
3    65.0
4    82.0
5    75.0
6    88.0
7    82.0
8    79.0
9    91.0
Name: performance, dtype: float64

In [29]:
df['remote'] = df['remote'].fillna(df['remote'].mode()[0])
df['remote']

0    Yes
1     No
2    Yes
3     No
4    Yes
5     No
6    Yes
7    Yes
8    Yes
9    Yes
Name: remote, dtype: object

In [30]:
#working with filter data
df.head()

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes
1,102,Micheal Smith,HR,35.0,4800.00,2020-11-01,73.0,No
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes
3,104,David Kim,IT,31.0,4800.00,2019-09-25,65.0,No
4,105,Unknown,Customer Care,42.0,6100.00,2018-07-05,82.0,Yes

In [31]:
df['full_name']

0    Alice Johnson
1    Micheal Smith
2        Sarah Lee
3        David Kim
4          Unknown
5       John Brown
6      Emma Wilson
7        Tom Davis
8      Jane Miller
9     Chris Taylor
Name: full_name, dtype: object

In [32]:
df[['full_name', 'department', 'salary']]

       full_name     department   salary
0  Alice Johnson             IT  5500.50
1  Micheal Smith             HR  4800.00
2      Sarah Lee      Marketing  4200.75
3      David Kim             IT  4800.00
4        Unknown  Customer Care  6100.00
5     John Brown      Marketing  4300.00
6    Emma Wilson        Finance  5800.00
7      Tom Davis      Marketing  5000.00
8    Jane Miller             HR  4700.00
9   Chris Taylor      Marketing  4400.00

In [33]:
df.iloc[0:3]

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes
1,102,Micheal Smith,HR,35.0,4800.00,2020-11-01,73.0,No
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes

In [34]:
df.iloc[0:3, 0:3]

   emp_id      full_name department
0     101  Alice Johnson         IT
1     102  Micheal Smith         HR
2     103      Sarah Lee  Marketing

In [35]:
df.loc[df['salary'] > 5000]

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29.0,5500.5,2021-04-12,87.0,Yes
4,105,Unknown,Customer Care,42.0,6100.0,2018-07-05,82.0,Yes
6,107,Emma Wilson,Finance,33.0,5800.0,2019-12-01,88.0,Yes

In [36]:
df.loc[df['salary'] > 5000, ['full_name', 'department']]

       full_name     department
0  Alice Johnson             IT
4        Unknown  Customer Care
6    Emma Wilson        Finance

In [37]:
df[df['department'] == 'IT']

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29.0,5500.5,2021-04-12,87.0,Yes
3,104,David Kim,IT,31.0,4800.0,2019-09-25,65.0,No

In [38]:
df[df['age'] > 25]

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes
1,102,Micheal Smith,HR,35.0,4800.00,2020-11-01,73.0,No
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes
3,104,David Kim,IT,31.0,4800.00,2019-09-25,65.0,No
4,105,Unknown,Customer Care,42.0,6100.00,2018-07-05,82.0,Yes
5,106,John Brown,Marketing,27.0,4300.00,2021-10-14,75.0,No
6,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Yes
7,108,Tom Davis,Marketing,30.0,5000.00,2020-03-22,82.0,Yes
8,109,Jane Miller,HR,30.0,4700.00,2021-05-10,79.0,Yes
9,110,Chris Taylor,Marketing,28.0,4400.00,2022-02-05,91.0,Yes

In [39]:
df[df['department'] != 'HR']

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes
3,104,David Kim,IT,31.0,4800.00,2019-09-25,65.0,No
4,105,Unknown,Customer Care,42.0,6100.00,2018-07-05,82.0,Yes
5,106,John Brown,Marketing,27.0,4300.00,2021-10-14,75.0,No
6,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Yes
7,108,Tom Davis,Marketing,30.0,5000.00,2020-03-22,82.0,Yes
9,110,Chris Taylor,Marketing,28.0,4400.00,2022-02-05,91.0,Yes

In [40]:
df[
    (df['salary'] > 4000) & (df['remote'] == 'Yes')
]

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes
4,105,Unknown,Customer Care,42.0,6100.00,2018-07-05,82.0,Yes
6,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Yes
7,108,Tom Davis,Marketing,30.0,5000.00,2020-03-22,82.0,Yes
8,109,Jane Miller,HR,30.0,4700.00,2021-05-10,79.0,Yes
9,110,Chris Taylor,Marketing,28.0,4400.00,2022-02-05,91.0,Yes

In [41]:
df[df['department'].isin(['IT', 'Finance'])]

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29.0,5500.5,2021-04-12,87.0,Yes
3,104,David Kim,IT,31.0,4800.0,2019-09-25,65.0,No
6,107,Emma Wilson,Finance,33.0,5800.0,2019-12-01,88.0,Yes

In [42]:
df[df['full_name'].str.contains('john', case=False)]

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29.0,5500.5,2021-04-12,87.0,Yes
5,106,John Brown,Marketing,27.0,4300.0,2021-10-14,75.0,No

In [43]:
df[df['department'].str.startswith('M')]

,emp_id,full_name,department,age,salary,join_date,performance,remote
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes
5,106,John Brown,Marketing,27.0,4300.00,2021-10-14,75.0,No
7,108,Tom Davis,Marketing,30.0,5000.00,2020-03-22,82.0,Yes
9,110,Chris Taylor,Marketing,28.0,4400.00,2022-02-05,91.0,Yes

In [44]:
#working with sorting
df.sort_values('salary', ascending=False)

,emp_id,full_name,department,age,salary,join_date,performance,remote
4,105,Unknown,Customer Care,42.0,6100.00,2018-07-05,82.0,Yes
6,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Yes
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes
7,108,Tom Davis,Marketing,30.0,5000.00,2020-03-22,82.0,Yes
1,102,Micheal Smith,HR,35.0,4800.00,2020-11-01,73.0,No
3,104,David Kim,IT,31.0,4800.00,2019-09-25,65.0,No
8,109,Jane Miller,HR,30.0,4700.00,2021-05-10,79.0,Yes
9,110,Chris Taylor,Marketing,28.0,4400.00,2022-02-05,91.0,Yes
5,106,John Brown,Marketing,27.0,4300.00,2021-10-14,75.0,No
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes

In [45]:
df.sort_values('performance', ascending=False).head()

,emp_id,full_name,department,age,salary,join_date,performance,remote
9,110,Chris Taylor,Marketing,28.0,4400.00,2022-02-05,91.0,Yes
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes
6,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Yes
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes
7,108,Tom Davis,Marketing,30.0,5000.00,2020-03-22,82.0,Yes

In [46]:
df.sort_values(['department', 'salary'], ascending=[True, False])

,emp_id,full_name,department,age,salary,join_date,performance,remote
4,105,Unknown,Customer Care,42.0,6100.00,2018-07-05,82.0,Yes
6,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Yes
1,102,Micheal Smith,HR,35.0,4800.00,2020-11-01,73.0,No
8,109,Jane Miller,HR,30.0,4700.00,2021-05-10,79.0,Yes
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes
3,104,David Kim,IT,31.0,4800.00,2019-09-25,65.0,No
7,108,Tom Davis,Marketing,30.0,5000.00,2020-03-22,82.0,Yes
9,110,Chris Taylor,Marketing,28.0,4400.00,2022-02-05,91.0,Yes
5,106,John Brown,Marketing,27.0,4300.00,2021-10-14,75.0,No
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes

In [47]:
#working with values count
df['department'].value_counts()

department
Marketing        4
IT               2
HR               2
Customer Care    1
Finance          1
Name: count, dtype: int64

In [48]:
df['department'].value_counts(normalize=True)*100

department
Marketing        40.0
IT               20.0
HR               20.0
Customer Care    10.0
Finance          10.0
Name: proportion, dtype: float64

In [49]:
df['remote'].value_counts(normalize=True)*100

remote
Yes    70.0
No     30.0
Name: proportion, dtype: float64

In [53]:
#working with merge
data1 = {
    "department": ["IT", "HR", "Finance", "Marketing", "R&D", "Operations", "Sales", "Logistics", "Procurement", "Customer Service"],
    "manager": [
        "Tom Hanks", "Susan Lee", "Robert Miles", 
        "Mark Chan", "Sarah Connor", "James Nwosu", "Adaeze Obi", 
        "Daniel Smith", "Amina Yusuf", "Grace Ojo"
    ],
    "department_budget": [200000, 150000, 250000, 180000, 300000, 220000, 210000, 195000, 230000, 170000],
    "office_location": [
        "Lagos", "Abuja", "Port Harcourt", "Ibadan", "Enugu", "Kano",
        "Lagos", "Calabar", "Abuja", "Kano"
    ]
}

df1 = pd.DataFrame(data1)
df1.to_csv("department_data.csv", index=False)

df1 = pd.read_csv("department_data.csv")
df1.head(10)

         department       manager  department_budget office_location
0                IT     Tom Hanks             200000           Lagos
1                HR     Susan Lee             150000           Abuja
2           Finance  Robert Miles             250000   Port Harcourt
3         Marketing     Mark Chan             180000          Ibadan
4               R&D  Sarah Connor             300000           Enugu
5        Operations   James Nwosu             220000            Kano
6             Sales    Adaeze Obi             210000           Lagos
7         Logistics  Daniel Smith             195000         Calabar
8       Procurement   Amina Yusuf             230000           Abuja
9  Customer Service     Grace Ojo             170000            Kano

In [54]:
merge_df = pd.merge(df, df1, how='inner')
merge_df

,emp_id,full_name,department,age,salary,join_date,performance,remote,manager,department_budget,office_location
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes,Tom Hanks,200000,Lagos
1,102,Micheal Smith,HR,35.0,4800.00,2020-11-01,73.0,No,Susan Lee,150000,Abuja
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes,Mark Chan,180000,Ibadan
3,104,David Kim,IT,31.0,4800.00,2019-09-25,65.0,No,Tom Hanks,200000,Lagos
4,106,John Brown,Marketing,27.0,4300.00,2021-10-14,75.0,No,Mark Chan,180000,Ibadan
5,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Yes,Robert Miles,250000,Port Harcourt
6,108,Tom Davis,Marketing,30.0,5000.00,2020-03-22,82.0,Yes,Mark Chan,180000,Ibadan
7,109,Jane Miller,HR,30.0,4700.00,2021-05-10,79.0,Yes,Susan Lee,150000,Abuja
8,110,Chris Taylor,Marketing,28.0,4400.00,2022-02-05,91.0,Yes,Mark Chan,180000,Ibadan

In [55]:
left_df = pd.merge(df, df1, how='left')
left_df

,emp_id,full_name,department,age,salary,join_date,performance,remote,manager,department_budget,office_location
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes,Tom Hanks,200000.0,Lagos
1,102,Micheal Smith,HR,35.0,4800.00,2020-11-01,73.0,No,Susan Lee,150000.0,Abuja
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes,Mark Chan,180000.0,Ibadan
3,104,David Kim,IT,31.0,4800.00,2019-09-25,65.0,No,Tom Hanks,200000.0,Lagos
4,105,Unknown,Customer Care,42.0,6100.00,2018-07-05,82.0,Yes,NaN,NaN,NaN
5,106,John Brown,Marketing,27.0,4300.00,2021-10-14,75.0,No,Mark Chan,180000.0,Ibadan
6,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Yes,Robert Miles,250000.0,Port Harcourt
7,108,Tom Davis,Marketing,30.0,5000.00,2020-03-22,82.0,Yes,Mark Chan,180000.0,Ibadan
8,109,Jane Miller,HR,30.0,4700.00,2021-05-10,79.0,Yes,Susan Lee,150000.0,Abuja
9,110,Chris Taylor,Marketing,28.0,4400.00,2022-02-05,91.0,Yes,Mark Chan,180000.0,Ibadan

In [56]:
right_df = pd.merge(df, df1, how='right')
right_df

,emp_id,full_name,department,age,salary,join_date,performance,remote,manager,department_budget,office_location
0,101.0,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes,Tom Hanks,200000,Lagos
1,104.0,David Kim,IT,31.0,4800.00,2019-09-25,65.0,No,Tom Hanks,200000,Lagos
2,102.0,Micheal Smith,HR,35.0,4800.00,2020-11-01,73.0,No,Susan Lee,150000,Abuja
3,109.0,Jane Miller,HR,30.0,4700.00,2021-05-10,79.0,Yes,Susan Lee,150000,Abuja
4,107.0,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Yes,Robert Miles,250000,Port Harcourt
5,103.0,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes,Mark Chan,180000,Ibadan
6,106.0,John Brown,Marketing,27.0,4300.00,2021-10-14,75.0,No,Mark Chan,180000,Ibadan
7,108.0,Tom Davis,Marketing,30.0,5000.00,2020-03-22,82.0,Yes,Mark Chan,180000,Ibadan
8,110.0,Chris Taylor,Marketing,28.0,4400.00,2022-02-05,91.0,Yes,Mark Chan,180000,Ibadan
9,NaN,NaN,R&D,NaN,NaN,NaT,NaN,NaN,Sarah Connor,300000,Enugu
10,NaN,NaN,Operations,NaN,NaN,NaT,NaN,NaN,James Nwosu,220000,Kano
11,NaN,NaN,Sales,NaN,NaN,NaT,NaN,NaN,Adaeze Obi,210000,Lagos
12,NaN,NaN,Logistics,NaN,NaN,NaT,NaN,NaN,Daniel Smith,195000,Calabar
13,NaN,NaN,Procurement,NaN,NaN,NaT,NaN,NaN,Amina Yusuf,230000,Abuja
14,NaN,NaN,Customer Service,NaN,NaN,NaT,NaN,NaN,Grace Ojo,170000,Kano

In [58]:
outter_df = pd.merge(df, df1, how='outer')
outter_df

,emp_id,full_name,department,age,salary,join_date,performance,remote,manager,department_budget,office_location
0,105.0,Unknown,Customer Care,42.0,6100.00,2018-07-05,82.0,Yes,NaN,NaN,NaN
1,NaN,NaN,Customer Service,NaN,NaN,NaT,NaN,NaN,Grace Ojo,170000.0,Kano
2,107.0,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Yes,Robert Miles,250000.0,Port Harcourt
3,102.0,Micheal Smith,HR,35.0,4800.00,2020-11-01,73.0,No,Susan Lee,150000.0,Abuja
4,109.0,Jane Miller,HR,30.0,4700.00,2021-05-10,79.0,Yes,Susan Lee,150000.0,Abuja
5,101.0,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes,Tom Hanks,200000.0,Lagos
6,104.0,David Kim,IT,31.0,4800.00,2019-09-25,65.0,No,Tom Hanks,200000.0,Lagos
7,NaN,NaN,Logistics,NaN,NaN,NaT,NaN,NaN,Daniel Smith,195000.0,Calabar
8,103.0,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes,Mark Chan,180000.0,Ibadan
9,106.0,John Brown,Marketing,27.0,4300.00,2021-10-14,75.0,No,Mark Chan,180000.0,Ibadan
10,108.0,Tom Davis,Marketing,30.0,5000.00,2020-03-22,82.0,Yes,Mark Chan,180000.0,Ibadan
11,110.0,Chris Taylor,Marketing,28.0,4400.00,2022-02-05,91.0,Yes,Mark Chan,180000.0,Ibadan
12,NaN,NaN,Operations,NaN,NaN,NaT,NaN,NaN,James Nwosu,220000.0,Kano
13,NaN,NaN,Procurement,NaN,NaN,NaT,NaN,NaN,Amina Yusuf,230000.0,Abuja
14,NaN,NaN,R&D,NaN,NaN,NaT,NaN,NaN,Sarah Connor,300000.0,Enugu
15,NaN,NaN,Sales,NaN,NaN,NaT,NaN,NaN,Adaeze Obi,210000.0,Lagos

In [60]:
print(merge_df['salary'].mean())

4833.472222222223

In [62]:
#working with groupby
#average salary by department
merge_df.groupby("department")["salary"].mean().sort_values(ascending=False)

department
Finance      5800.0000
IT           5150.2500
HR           4750.0000
Marketing    4475.1875
Name: salary, dtype: float64

In [63]:
#average performance by department
merge_df.groupby("department")["performance"].mean().sort_values(ascending=False)

department
Finance      88.0
Marketing    84.5
HR           76.0
IT           76.0
Name: performance, dtype: float64

In [65]:
#average performance by department and remote
merge_df.groupby(["department", "remote"])["performance"].mean().sort_values(ascending=False)

department  remote
Finance     Yes       88.000000
Marketing   Yes       87.666667
IT          Yes       87.000000
HR          Yes       79.000000
Marketing   No        75.000000
HR          No        73.000000
IT          No        65.000000
Name: performance, dtype: float64

In [69]:
#working with multiple aggregation
merge_df.groupby("department")["salary"].agg({'mean', 'count', 'min', 'max'})

                min       mean  count     max
department
Finance     5800.00  5800.0000      1  5800.0
HR          4700.00  4750.0000      2  4800.0
IT          4800.00  5150.2500      2  5500.5
Marketing   4200.75  4475.1875      4  5000.0

In [71]:
#working with multiple columns apply to several
merge_df.groupby("department")[['salary', 'performance']].mean().sort_values(by='salary', ascending=False)

               salary  performance
department
Finance     5800.0000         88.0
IT          5150.2500         76.0
HR          4750.0000         76.0
Marketing   4475.1875         84.5

In [73]:
#working with multiple aggregation
merge_df.groupby("department").agg(
    average_salary=('salary', 'mean'),
    highest_salary=('salary', 'max'),
    lowest_salary=('salary', 'min'),
    employee_count=('salary', 'count')
)

            average_salary  highest_salary  lowest_salary  employee_count
department
Finance          5800.0000          5800.0        5800.00               1
HR               4750.0000          4800.0        4700.00               2
IT               5150.2500          5500.5        4800.00               2
Marketing        4475.1875          5000.0        4200.75               4

In [74]:
#working with multiple aggregation
merge_df.groupby("department").agg(
    average_salary=('salary', 'mean'),
    avg_performance=('performance', 'mean'),
    total_employee=('emp_id', 'count')
)

            average_salary  avg_performance  total_employee
department
Finance          5800.0000             88.0               1
HR               4750.0000             76.0               2
IT               5150.2500             76.0               2
Marketing        4475.1875             84.5               4

In [76]:
#group column by salary using reset_index
merge_df.groupby("department")["salary"].mean().reset_index()

  department     salary
0    Finance  5800.0000
1         HR  4750.0000
2         IT  5150.2500
3  Marketing  4475.1875

In [77]:
merge_df.groupby("department")["salary"].apply(lambda x: x.std())

department
Finance             NaN
HR            70.710678
IT           495.328300
Marketing    359.206497
Name: salary, dtype: float64

In [79]:
merge_df.groupby("department").filter(lambda x: x['salary'].mean() > 5000)

,emp_id,full_name,department,age,salary,join_date,performance,remote,manager,department_budget,office_location
0,101,Alice Johnson,IT,29.0,5500.5,2021-04-12,87.0,Yes,Tom Hanks,200000,Lagos
3,104,David Kim,IT,31.0,4800.0,2019-09-25,65.0,No,Tom Hanks,200000,Lagos
5,107,Emma Wilson,Finance,33.0,5800.0,2019-12-01,88.0,Yes,Robert Miles,250000,Port Harcourt

In [81]:
merge_df['department_avg_salary'] = merge_df.groupby('department')['salary'].transform('mean')
merge_df

,emp_id,full_name,department,age,salary,join_date,performance,remote,manager,department_budget,office_location,department_avg_salary
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes,Tom Hanks,200000,Lagos,5150.2500
1,102,Micheal Smith,HR,35.0,4800.00,2020-11-01,73.0,No,Susan Lee,150000,Abuja,4750.0000
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes,Mark Chan,180000,Ibadan,4475.1875
3,104,David Kim,IT,31.0,4800.00,2019-09-25,65.0,No,Tom Hanks,200000,Lagos,5150.2500
4,106,John Brown,Marketing,27.0,4300.00,2021-10-14,75.0,No,Mark Chan,180000,Ibadan,4475.1875
5,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Yes,Robert Miles,250000,Port Harcourt,5800.0000
6,108,Tom Davis,Marketing,30.0,5000.00,2020-03-22,82.0,Yes,Mark Chan,180000,Ibadan,4475.1875
7,109,Jane Miller,HR,30.0,4700.00,2021-05-10,79.0,Yes,Susan Lee,150000,Abuja,4750.0000
8,110,Chris Taylor,Marketing,28.0,4400.00,2022-02-05,91.0,Yes,Mark Chan,180000,Ibadan,4475.1875

In [82]:
merge_df.groupby('department')['salary'].apply(lambda x: x.max() - x.min())

department
Finance        0.00
HR           100.00
IT           700.50
Marketing    799.25
Name: salary, dtype: float64