In [39]:
import pandas as pd
import numpy as np

In [40]:
#create sample messy employee data
data = {
    "EmpId": [101, 102, "103", 104, 105, 106, 107, 108, 109, 110],
    "fullName": [
        "  Alice Johnson  ", "MICHEAL smith", "sarah lee", "David-Kim", None, "john brown",
        "Emma Wilson", "TOM  davis", "Jane Miller", "Chris taylor"
    ], 
     "Dept": ["IT", "hr", "Mktng", "IT", "Customer Care", "marketing", "Finance", None, "HR", "marketing"],
    "Age": [29, "thirty-five", 26, 31, 42, 27, 33, 30, None, 28],
    "Salary($)": ["$5500.50", "4800", "4200.75", "NaN", "6100", "4,300", "5800", "5000", "4700.0", "4400"],
    "JoinDate": [
        "2021/04/12", "2020/11/01", "2022/01/18", "2019/9/25", "2018/07/05", 
        "2021/10/14", "2019/12/01", "2020/03/22", "2021/05/10", "2022/02/05"
    ],
    "Performance": [87, "73", 90, 65, 82, 75, 88, None, "79%", "91"],
    "Remote?": ["Yes", "No", "Y", "N", "yes", "no", "Y", "Yes", None, "True"]
}

In [41]:
df = pd.DataFrame(data)

df.to_csv("employee_dataset.csv", index=False)

df = pd.read_csv("employee_dataset.csv")

df

,EmpId,fullName,Dept,Age,Salary($),JoinDate,Performance,Remote?
0,101,Alice Johnson,IT,29,$5500.50,2021/04/12,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020/11/01,73,No
2,103,sarah lee,Mktng,26,4200.75,2022/01/18,90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,2018/07/05,82,yes
5,106,john brown,marketing,27,"4,300",2021/10/14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,TOM davis,NaN,30,5000,2020/03/22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.0,2021/05/10,79%,NaN
9,110,Chris taylor,marketing,28,4400,2022/02/05,91,True

In [42]:
#get the dataframe shapes
df.shape

(10, 8)

In [43]:
#get the information of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmpId        10 non-null     int64
 1   fullName     9 non-null      object
 2   Dept         9 non-null      object
 3   Age          9 non-null      object
 4   Salary($)    9 non-null      object
 5   JoinDate     10 non-null     object
 6   Performance  9 non-null      object
 7   Remote?      9 non-null      object
dtypes: int64(1), object(7)
memory usage: 768.0+ bytes

In [44]:
#get first five rows of the dataset
df.head()

,EmpId,fullName,Dept,Age,Salary($),JoinDate,Performance,Remote?
0,101,Alice Johnson,IT,29,$5500.50,2021/04/12,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020/11/01,73,No
2,103,sarah lee,Mktng,26,4200.75,2022/01/18,90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,2018/07/05,82,yes

In [45]:
#get columns for the dataset
df.columns

Index(['EmpId', 'fullName', 'Dept', 'Age', 'Salary($)', 'JoinDate',
       'Performance', 'Remote?'],
      dtype='object')

In [46]:
#get missing values
df.isnull().sum()

EmpId          0
fullName       1
Dept           1
Age            1
Salary($)      1
JoinDate       0
Performance    1
Remote?        1
dtype: int64

In [47]:
#get uniqueness of the dataset
print(df["Dept"].unique())
print(df['Age'].unique())
print(df['Remote?'].unique())

['IT' 'hr' 'Mktng' 'Customer Care' 'marketing' 'Finance' nan 'HR']
['29' 'thirty-five' '26' '31' '42' '27' '33' '30' nan '28']
['Yes' 'No' 'Y' 'N' 'yes' 'no' nan 'True']

In [48]:
#access series data
df["Salary($)"].tolist()

['$5500.50',
 '4800',
 '4200.75',
 nan,
 '6100',
 '4,300',
 '5800',
 '5000',
 '4700.0',
 '4400']

In [49]:
df['fullName'].tolist()

['  Alice Johnson  ',
 'MICHEAL smith',
 'sarah lee',
 'David-Kim',
 nan,
 'john brown',
 'Emma Wilson',
 'TOM  davis',
 'Jane Miller',
 'Chris taylor']

In [50]:
df['Salary($)'].head()

0    $5500.50
1        4800
2     4200.75
3         NaN
4        6100
Name: Salary($), dtype: object

In [51]:
#start cleaning inconsistence valus
#rename inconsistence columns
df.rename(columns={
    'EmpId': 'emp_id',
    'fullName': 'full_name',
    'Dept': 'department',
    'Age': 'age',
    'Salary($)': 'salary',
    'JoinDate': 'join_date',
    'Performance': 'performance',
    'Remote?': 'remote'
}, inplace=True)

df

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29,$5500.50,2021/04/12,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020/11/01,73,No
2,103,sarah lee,Mktng,26,4200.75,2022/01/18,90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,2018/07/05,82,yes
5,106,john brown,marketing,27,"4,300",2021/10/14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,TOM davis,NaN,30,5000,2020/03/22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.0,2021/05/10,79%,NaN
9,110,Chris taylor,marketing,28,4400,2022/02/05,91,True

In [52]:
df['full_name'] = df['full_name'].str.strip()
df['full_name'] = df['full_name'].str.title()
df['full_name'] = df['full_name'].str.replace(r"\s+", " ", regex=True)
df['full_name'] = df['full_name'].str.replace(r"-", " ")
df['full_name'].tolist()

['Alice Johnson',
 'Micheal Smith',
 'Sarah Lee',
 'David Kim',
 nan,
 'John Brown',
 'Emma Wilson',
 'Tom Davis',
 'Jane Miller',
 'Chris Taylor']

In [53]:
#clean inconsistent values on department
df["department"].replace({
    "hr": "HR",
    "Mktng": "Marketing",
    "marketing": "Marketing"
}, inplace=True)

df

C:\Users\ola-dev\AppData\Local\Temp\ipykernel_20040\4184915569.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["department"].replace({

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29,$5500.50,2021/04/12,87,Yes
1,102,Micheal Smith,HR,thirty-five,4800,2020/11/01,73,No
2,103,Sarah Lee,Marketing,26,4200.75,2022/01/18,90,Y
3,104,David Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,2018/07/05,82,yes
5,106,John Brown,Marketing,27,"4,300",2021/10/14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,Tom Davis,NaN,30,5000,2020/03/22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.0,2021/05/10,79%,NaN
9,110,Chris Taylor,Marketing,28,4400,2022/02/05,91,True

In [54]:
#clean inconsistent values on age
def clean_age(value):
    if value == "thirty-five":
        return 35
    elif isinstance(value, (int, float)):
        return value
    elif isinstance(value, str) and value.isdigit():
        return int(value)
    else:
        return np.nan

df['age'] = df['age'].apply(clean_age)

df['age']

0    29.0
1    35.0
2    26.0
3    31.0
4    42.0
5    27.0
6    33.0
7    30.0
8     NaN
9    28.0
Name: age, dtype: float64

In [55]:
#clean inconsistent value on salary
df["salary"] = (
    df["salary"]
    .astype(str)
    .replace(r"[$,]", "", regex=True)
    .replace("NAN", np.nan)
    .astype(float)
)

df["salary"]

0    5500.50
1    4800.00
2    4200.75
3        NaN
4    6100.00
5    4300.00
6    5800.00
7    5000.00
8    4700.00
9    4400.00
Name: salary, dtype: float64

In [56]:
df['join_date'] = pd.to_datetime(df['join_date'], errors='coerce')
df['join_date']

0   2021-04-12
1   2020-11-01
2   2022-01-18
3   2019-09-25
4   2018-07-05
5   2021-10-14
6   2019-12-01
7   2020-03-22
8   2021-05-10
9   2022-02-05
Name: join_date, dtype: datetime64[ns]

In [57]:
#clean inconsistent value in performance
df['performance'] = (
    df['performance']
    .astype(str)
    .str.replace('%', '', regex=False)
    .replace("None", np.nan)
    .astype(float)
)

df['performance']

0    87.0
1    73.0
2    90.0
3    65.0
4    82.0
5    75.0
6    88.0
7     NaN
8    79.0
9    91.0
Name: performance, dtype: float64

In [58]:
#clean inconsistent value on remote
df['remote'].replace({
    'Y': 'Yes',
    'N': 'No',
    'yes': 'Yes',
    'no': 'No',
    'True': 'Yes',
    None: np.nan
}, inplace=True)

df['remote']

C:\Users\ola-dev\AppData\Local\Temp\ipykernel_20040\481794493.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['remote'].replace({

0    Yes
1     No
2    Yes
3     No
4    Yes
5     No
6    Yes
7    Yes
8    NaN
9    Yes
Name: remote, dtype: object

In [59]:
#clean inconsistent empid value
df["emp_id"] = pd.to_numeric(df["emp_id"], errors='coerce')
df['emp_id']

0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
8    109
9    110
Name: emp_id, dtype: int64

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   emp_id       10 non-null     int64
 1   full_name    9 non-null      object
 2   department   9 non-null      object
 3   age          9 non-null      float64
 4   salary       9 non-null      float64
 5   join_date    10 non-null     datetime64[ns]
 6   performance  9 non-null      float64
 7   remote       9 non-null      object
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 768.0+ bytes

In [61]:
#handling missing value
df['full_name'] = df['full_name'].fillna("Unknown")
df['full_name']

0    Alice Johnson
1    Micheal Smith
2        Sarah Lee
3        David Kim
4          Unknown
5       John Brown
6      Emma Wilson
7        Tom Davis
8      Jane Miller
9     Chris Taylor
Name: full_name, dtype: object

In [64]:
df['department'] = df['department'].fillna(df['department'].mode()[0])
df['department']

0               IT
1               HR
2        Marketing
3               IT
4    Customer Care
5        Marketing
6          Finance
7        Marketing
8               HR
9        Marketing
Name: department, dtype: object

In [67]:
df['age'] = df['age'].fillna(df['age'].median())
df['age']

0    29.0
1    35.0
2    26.0
3    31.0
4    42.0
5    27.0
6    33.0
7    30.0
8    30.0
9    28.0
Name: age, dtype: float64

In [70]:
df['salary'] = df['salary'].fillna(df['salary'].median())
df['salary']

0    5500.50
1    4800.00
2    4200.75
3    4800.00
4    6100.00
5    4300.00
6    5800.00
7    5000.00
8    4700.00
9    4400.00
Name: salary, dtype: float64

In [72]:
df['performance'] = df['performance'].fillna(df['performance'].median())
df['performance']

0    87.0
1    73.0
2    90.0
3    65.0
4    82.0
5    75.0
6    88.0
7    82.0
8    79.0
9    91.0
Name: performance, dtype: float64

In [75]:
df['remote'] = df['remote'].fillna(df['remote'].mode()[0])
df['remote']

0    Yes
1     No
2    Yes
3     No
4    Yes
5     No
6    Yes
7    Yes
8    Yes
9    Yes
Name: remote, dtype: object

In [76]:
#working with filter data
df.head()

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes
1,102,Micheal Smith,HR,35.0,4800.00,2020-11-01,73.0,No
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes
3,104,David Kim,IT,31.0,4800.00,2019-09-25,65.0,No
4,105,Unknown,Customer Care,42.0,6100.00,2018-07-05,82.0,Yes

In [79]:
df['full_name']

0    Alice Johnson
1    Micheal Smith
2        Sarah Lee
3        David Kim
4          Unknown
5       John Brown
6      Emma Wilson
7        Tom Davis
8      Jane Miller
9     Chris Taylor
Name: full_name, dtype: object

In [80]:
df[['full_name', 'department', 'salary']]

       full_name     department   salary
0  Alice Johnson             IT  5500.50
1  Micheal Smith             HR  4800.00
2      Sarah Lee      Marketing  4200.75
3      David Kim             IT  4800.00
4        Unknown  Customer Care  6100.00
5     John Brown      Marketing  4300.00
6    Emma Wilson        Finance  5800.00
7      Tom Davis      Marketing  5000.00
8    Jane Miller             HR  4700.00
9   Chris Taylor      Marketing  4400.00