In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    "Product_ID": ["P001","P002","P003","P004","P005","P005","P006","P007","P008","P009","P010","P011","P012","P013","P014","P015","P016","P017","P018","P019","P020"],
    "Product_Name": ["HP laptop",None," HP keyboard","Infinix Phone","iphone headphone","iphone headphone","tecno PHONE","DELL LAPTOP"," accer LapTOP","Dell Keyboard","Tecno Tablet","Itel PHONE","tecno Headphone","TELEVISION","Remote","oraimo Headphone","samsung Laptop","Bulb","samsung Phone","HP Laptop","Dell Laptop"],
    "Category": ["electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electrical","Electronics","Electronics","Electronics"],
    "Supplier": ["jumia","Femtech","jumia","Jumia","femotech","femotech","Jumia","Femtech","Femtech","Jumia","Femtech","Femtech","Femtech","Femtech","Femtech","Femtech","Jumia","Femtech","juma","Femtech","Femtech"],  
    "Quantity":[11,20,21,5,30,30,7,10,12,19,14,12,15,5,"five",15,5,25,13,8,9],
    "Unit price($)": [1200,500,50,150,100,100,120,800,750,30,200,90,25,550,15,30,1000,5,1000,950,900],
    "Reorder_Level":[5,12,10,2,20,20,2,3,4,2,11,4,2,2,1,5,3,2,4,3,4],
    "Last_Update": ["2025/01/01","2025/01/08","2025/01/22","2025/01/30","2025/02/01","2025/02/01","2025/02/21","2025/02/28","2025/03/01","2025/03/08","2025/03/21","2025/03/28","2025/04/01","2025/04/08","2025/04/21","2025/04/28","2025/05/01","2025/05/08","2025/05/15","2025/05/21","2025/05/28"]
}

In [3]:
df = pd.DataFrame(data)
df.to_csv("sales_product.csv" , index=False)
df = pd.read_csv("sales_product.csv")

df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit price($),Reorder_Level,Last_Update
0,P001,HP laptop,electronics,jumia,11,1200,5,2025/01/01
1,P002,NaN,Electronics,Femtech,20,500,12,2025/01/08
2,P003,HP keyboard,Electronics,jumia,21,50,10,2025/01/22
3,P004,Infinix Phone,Electronics,Jumia,5,150,2,2025/01/30
4,P005,iphone headphone,Electronics,femotech,30,100,20,2025/02/01
5,P005,iphone headphone,Electronics,femotech,30,100,20,2025/02/01
6,P006,tecno PHONE,Electronics,Jumia,7,120,2,2025/02/21
7,P007,DELL LAPTOP,Electronics,Femtech,10,800,3,2025/02/28
8,P008,accer LapTOP,Electronics,Femtech,12,750,4,2025/03/01
9,P009,Dell Keyboard,Electronics,Jumia,19,30,2,2025/03/08
10,P010,Tecno Tablet,Electronics,Femtech,14,200,11,2025/03/21
11,P011,Itel PHONE,Electronics,Femtech,12,90,4,2025/03/28
12,P012,tecno Headphone,Electronics,Femtech,15,25,2,2025/04/01
13,P013,TELEVISION,Electronics,Femtech,5,550,2,2025/04/08
14,P014,Remote,Electronics,Femtech,five,15,1,2025/04/21
15,P015,oraimo Headphone,Electronics,Femtech,15,30,5,2025/04/28
16,P016,samsung Laptop,Electronics,Jumia,5,1000,3,2025/05/01
17,P017,Bulb,Electrical,Femtech,25,5,2,2025/05/08
18,P018,samsung Phone,Electronics,juma,13,1000,4,2025/05/15
19,P019,HP Laptop,Electronics,Femtech,8,950,3,2025/05/21
20,P020,Dell Laptop,Electronics,Femtech,9,900,4,2025/05/28

In [4]:
#display the first 5 rows

df.head()

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit price($),Reorder_Level,Last_Update
0,P001,HP laptop,electronics,jumia,11,1200,5,2025/01/01
1,P002,NaN,Electronics,Femtech,20,500,12,2025/01/08
2,P003,HP keyboard,Electronics,jumia,21,50,10,2025/01/22
3,P004,Infinix Phone,Electronics,Jumia,5,150,2,2025/01/30
4,P005,iphone headphone,Electronics,femotech,30,100,20,2025/02/01

In [5]:
#display the last 5 rows

df.tail()

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit price($),Reorder_Level,Last_Update
16,P016,samsung Laptop,Electronics,Jumia,5,1000,3,2025/05/01
17,P017,Bulb,Electrical,Femtech,25,5,2,2025/05/08
18,P018,samsung Phone,Electronics,juma,13,1000,4,2025/05/15
19,P019,HP Laptop,Electronics,Femtech,8,950,3,2025/05/21
20,P020,Dell Laptop,Electronics,Femtech,9,900,4,2025/05/28

In [6]:
#show basic information about the data set

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product_ID     21 non-null     object
 1   Product_Name   20 non-null     object
 2   Category       21 non-null     object
 3   Supplier       21 non-null     object
 4   Quantity       21 non-null     object
 5   Unit price($)  21 non-null     int64
 6   Reorder_Level  21 non-null     int64
 7   Last_Update    21 non-null     object
dtypes: int64(2), object(6)
memory usage: 1.4+ KB

In [7]:
df.describe()

       Unit price($)  Reorder_Level
count      21.000000      21.000000
mean      407.857143       5.761905
std       419.784383       5.629429
min         5.000000       1.000000
25%        50.000000       2.000000
50%       150.000000       4.000000
75%       800.000000       5.000000
max      1200.000000      20.000000

In [8]:
#remove duplicate row

df = df.drop_duplicates()

df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit price($),Reorder_Level,Last_Update
0,P001,HP laptop,electronics,jumia,11,1200,5,2025/01/01
1,P002,NaN,Electronics,Femtech,20,500,12,2025/01/08
2,P003,HP keyboard,Electronics,jumia,21,50,10,2025/01/22
3,P004,Infinix Phone,Electronics,Jumia,5,150,2,2025/01/30
4,P005,iphone headphone,Electronics,femotech,30,100,20,2025/02/01
6,P006,tecno PHONE,Electronics,Jumia,7,120,2,2025/02/21
7,P007,DELL LAPTOP,Electronics,Femtech,10,800,3,2025/02/28
8,P008,accer LapTOP,Electronics,Femtech,12,750,4,2025/03/01
9,P009,Dell Keyboard,Electronics,Jumia,19,30,2,2025/03/08
10,P010,Tecno Tablet,Electronics,Femtech,14,200,11,2025/03/21
11,P011,Itel PHONE,Electronics,Femtech,12,90,4,2025/03/28
12,P012,tecno Headphone,Electronics,Femtech,15,25,2,2025/04/01
13,P013,TELEVISION,Electronics,Femtech,5,550,2,2025/04/08
14,P014,Remote,Electronics,Femtech,five,15,1,2025/04/21
15,P015,oraimo Headphone,Electronics,Femtech,15,30,5,2025/04/28
16,P016,samsung Laptop,Electronics,Jumia,5,1000,3,2025/05/01
17,P017,Bulb,Electrical,Femtech,25,5,2,2025/05/08
18,P018,samsung Phone,Electronics,juma,13,1000,4,2025/05/15
19,P019,HP Laptop,Electronics,Femtech,8,950,3,2025/05/21
20,P020,Dell Laptop,Electronics,Femtech,9,900,4,2025/05/28

In [9]:
df["Product_ID"].unique()

array(['P001', 'P002', 'P003', 'P004', 'P005', 'P006', 'P007', 'P008',
       'P009', 'P010', 'P011', 'P012', 'P013', 'P014', 'P015', 'P016',
       'P017', 'P018', 'P019', 'P020'], dtype=object)

In [10]:
df["Product_Name"].tolist()

['HP laptop',
 nan,
 ' HP keyboard',
 'Infinix Phone',
 'iphone headphone',
 'tecno PHONE',
 'DELL LAPTOP',
 ' accer LapTOP',
 'Dell Keyboard',
 'Tecno Tablet',
 'Itel PHONE',
 'tecno Headphone',
 'TELEVISION',
 'Remote',
 'oraimo Headphone',
 'samsung Laptop',
 'Bulb',
 'samsung Phone',
 'HP Laptop',
 'Dell Laptop']

In [11]:
#remove space

df["Product_Name"] = df["Product_Name"].str.strip()

df["Product_Name"].tolist()

C:\Users\ola-dev\AppData\Local\Temp\ipykernel_22652\631508330.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Product_Name"] = df["Product_Name"].str.strip()

['HP laptop',
 nan,
 'HP keyboard',
 'Infinix Phone',
 'iphone headphone',
 'tecno PHONE',
 'DELL LAPTOP',
 'accer LapTOP',
 'Dell Keyboard',
 'Tecno Tablet',
 'Itel PHONE',
 'tecno Headphone',
 'TELEVISION',
 'Remote',
 'oraimo Headphone',
 'samsung Laptop',
 'Bulb',
 'samsung Phone',
 'HP Laptop',
 'Dell Laptop']

In [12]:
#capitalize word

df["Product_Name"] = df["Product_Name"].str.title()

df["Product_Name"].tolist()

C:\Users\ola-dev\AppData\Local\Temp\ipykernel_22652\3799285994.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Product_Name"] = df["Product_Name"].str.title()

['Hp Laptop',
 nan,
 'Hp Keyboard',
 'Infinix Phone',
 'Iphone Headphone',
 'Tecno Phone',
 'Dell Laptop',
 'Accer Laptop',
 'Dell Keyboard',
 'Tecno Tablet',
 'Itel Phone',
 'Tecno Headphone',
 'Television',
 'Remote',
 'Oraimo Headphone',
 'Samsung Laptop',
 'Bulb',
 'Samsung Phone',
 'Hp Laptop',
 'Dell Laptop']

In [13]:
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit price($),Reorder_Level,Last_Update
0,P001,Hp Laptop,electronics,jumia,11,1200,5,2025/01/01
1,P002,NaN,Electronics,Femtech,20,500,12,2025/01/08
2,P003,Hp Keyboard,Electronics,jumia,21,50,10,2025/01/22
3,P004,Infinix Phone,Electronics,Jumia,5,150,2,2025/01/30
4,P005,Iphone Headphone,Electronics,femotech,30,100,20,2025/02/01
6,P006,Tecno Phone,Electronics,Jumia,7,120,2,2025/02/21
7,P007,Dell Laptop,Electronics,Femtech,10,800,3,2025/02/28
8,P008,Accer Laptop,Electronics,Femtech,12,750,4,2025/03/01
9,P009,Dell Keyboard,Electronics,Jumia,19,30,2,2025/03/08
10,P010,Tecno Tablet,Electronics,Femtech,14,200,11,2025/03/21
11,P011,Itel Phone,Electronics,Femtech,12,90,4,2025/03/28
12,P012,Tecno Headphone,Electronics,Femtech,15,25,2,2025/04/01
13,P013,Television,Electronics,Femtech,5,550,2,2025/04/08
14,P014,Remote,Electronics,Femtech,five,15,1,2025/04/21
15,P015,Oraimo Headphone,Electronics,Femtech,15,30,5,2025/04/28
16,P016,Samsung Laptop,Electronics,Jumia,5,1000,3,2025/05/01
17,P017,Bulb,Electrical,Femtech,25,5,2,2025/05/08
18,P018,Samsung Phone,Electronics,juma,13,1000,4,2025/05/15
19,P019,Hp Laptop,Electronics,Femtech,8,950,3,2025/05/21
20,P020,Dell Laptop,Electronics,Femtech,9,900,4,2025/05/28

In [14]:
#Replace nan to np.nan

df["Product_Name"] = (
    df["Product_Name"]
    .astype(str)
    .replace("NaN" , np.nan)
)

df

C:\Users\ola-dev\AppData\Local\Temp\ipykernel_22652\418791335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Product_Name"] = (

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit price($),Reorder_Level,Last_Update
0,P001,Hp Laptop,electronics,jumia,11,1200,5,2025/01/01
1,P002,nan,Electronics,Femtech,20,500,12,2025/01/08
2,P003,Hp Keyboard,Electronics,jumia,21,50,10,2025/01/22
3,P004,Infinix Phone,Electronics,Jumia,5,150,2,2025/01/30
4,P005,Iphone Headphone,Electronics,femotech,30,100,20,2025/02/01
6,P006,Tecno Phone,Electronics,Jumia,7,120,2,2025/02/21
7,P007,Dell Laptop,Electronics,Femtech,10,800,3,2025/02/28
8,P008,Accer Laptop,Electronics,Femtech,12,750,4,2025/03/01
9,P009,Dell Keyboard,Electronics,Jumia,19,30,2,2025/03/08
10,P010,Tecno Tablet,Electronics,Femtech,14,200,11,2025/03/21
11,P011,Itel Phone,Electronics,Femtech,12,90,4,2025/03/28
12,P012,Tecno Headphone,Electronics,Femtech,15,25,2,2025/04/01
13,P013,Television,Electronics,Femtech,5,550,2,2025/04/08
14,P014,Remote,Electronics,Femtech,five,15,1,2025/04/21
15,P015,Oraimo Headphone,Electronics,Femtech,15,30,5,2025/04/28
16,P016,Samsung Laptop,Electronics,Jumia,5,1000,3,2025/05/01
17,P017,Bulb,Electrical,Femtech,25,5,2,2025/05/08
18,P018,Samsung Phone,Electronics,juma,13,1000,4,2025/05/15
19,P019,Hp Laptop,Electronics,Femtech,8,950,3,2025/05/21
20,P020,Dell Laptop,Electronics,Femtech,9,900,4,2025/05/28

In [15]:
df["Category"].tolist()

['electronics',
 'Electronics',
 'Electronics',
 'Electronics',
 'Electronics',
 'Electronics',
 'Electronics',
 'Electronics',
 'Electronics',
 'Electronics',
 'Electronics',
 'Electronics',
 'Electronics',
 'Electronics',
 'Electronics',
 'Electronics',
 'Electrical',
 'Electronics',
 'Electronics',
 'Electronics']

In [16]:
#remove space and capitalize word

df["Category"] = df["Category"].str.strip()
df["Category"] = df["Category"].str.title()
df["Category"].tolist

C:\Users\ola-dev\AppData\Local\Temp\ipykernel_22652\1941371348.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Category"] = df["Category"].str.strip()
C:\Users\ola-dev\AppData\Local\Temp\ipykernel_22652\1941371348.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Category"] = df["Category"].str.title()

<bound method IndexOpsMixin.tolist of 0     Electronics
1     Electronics
2     Electronics
3     Electronics
4     Electronics
6     Electronics
7     Electronics
8     Electronics
9     Electronics
10    Electronics
11    Electronics
12    Electronics
13    Electronics
14    Electronics
15    Electronics
16    Electronics
17     Electrical
18    Electronics
19    Electronics
20    Electronics
Name: Category, dtype: object>

In [17]:
df["Supplier"].unique()

array(['jumia', 'Femtech', 'Jumia', 'femotech', 'juma'], dtype=object)

In [18]:
df["Supplier"] = (
   df["Supplier"]
    .astype(str)
    .replace({
        "jumia":"Jumia",
        "femotech":"Femtech",
        "juma":"Jumia"
    })
)

df["Supplier"].tolist()

C:\Users\ola-dev\AppData\Local\Temp\ipykernel_22652\3444888870.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Supplier"] = (

['Jumia',
 'Femtech',
 'Jumia',
 'Jumia',
 'Femtech',
 'Jumia',
 'Femtech',
 'Femtech',
 'Jumia',
 'Femtech',
 'Femtech',
 'Femtech',
 'Femtech',
 'Femtech',
 'Femtech',
 'Jumia',
 'Femtech',
 'Jumia',
 'Femtech',
 'Femtech']

In [19]:
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit price($),Reorder_Level,Last_Update
0,P001,Hp Laptop,Electronics,Jumia,11,1200,5,2025/01/01
1,P002,nan,Electronics,Femtech,20,500,12,2025/01/08
2,P003,Hp Keyboard,Electronics,Jumia,21,50,10,2025/01/22
3,P004,Infinix Phone,Electronics,Jumia,5,150,2,2025/01/30
4,P005,Iphone Headphone,Electronics,Femtech,30,100,20,2025/02/01
6,P006,Tecno Phone,Electronics,Jumia,7,120,2,2025/02/21
7,P007,Dell Laptop,Electronics,Femtech,10,800,3,2025/02/28
8,P008,Accer Laptop,Electronics,Femtech,12,750,4,2025/03/01
9,P009,Dell Keyboard,Electronics,Jumia,19,30,2,2025/03/08
10,P010,Tecno Tablet,Electronics,Femtech,14,200,11,2025/03/21
11,P011,Itel Phone,Electronics,Femtech,12,90,4,2025/03/28
12,P012,Tecno Headphone,Electronics,Femtech,15,25,2,2025/04/01
13,P013,Television,Electronics,Femtech,5,550,2,2025/04/08
14,P014,Remote,Electronics,Femtech,five,15,1,2025/04/21
15,P015,Oraimo Headphone,Electronics,Femtech,15,30,5,2025/04/28
16,P016,Samsung Laptop,Electronics,Jumia,5,1000,3,2025/05/01
17,P017,Bulb,Electrical,Femtech,25,5,2,2025/05/08
18,P018,Samsung Phone,Electronics,Jumia,13,1000,4,2025/05/15
19,P019,Hp Laptop,Electronics,Femtech,8,950,3,2025/05/21
20,P020,Dell Laptop,Electronics,Femtech,9,900,4,2025/05/28

In [20]:
def clean_Quantity(value):
    if value == "five":
       return 5
    elif isinstance(value ,(int , float)):
        return value
    elif isinstance(value, str) and value.isdigit():
        return int(value)
    else : 
          return np.nan
df["Quantity"] = df["Quantity"].apply(clean_Quantity)

df["Quantity"]

C:\Users\ola-dev\AppData\Local\Temp\ipykernel_22652\748691656.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Quantity"] = df["Quantity"].apply(clean_Quantity)

0     11
1     20
2     21
3      5
4     30
6      7
7     10
8     12
9     19
10    14
11    12
12    15
13     5
14     5
15    15
16     5
17    25
18    13
19     8
20     9
Name: Quantity, dtype: int64

In [21]:
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit price($),Reorder_Level,Last_Update
0,P001,Hp Laptop,Electronics,Jumia,11,1200,5,2025/01/01
1,P002,nan,Electronics,Femtech,20,500,12,2025/01/08
2,P003,Hp Keyboard,Electronics,Jumia,21,50,10,2025/01/22
3,P004,Infinix Phone,Electronics,Jumia,5,150,2,2025/01/30
4,P005,Iphone Headphone,Electronics,Femtech,30,100,20,2025/02/01
6,P006,Tecno Phone,Electronics,Jumia,7,120,2,2025/02/21
7,P007,Dell Laptop,Electronics,Femtech,10,800,3,2025/02/28
8,P008,Accer Laptop,Electronics,Femtech,12,750,4,2025/03/01
9,P009,Dell Keyboard,Electronics,Jumia,19,30,2,2025/03/08
10,P010,Tecno Tablet,Electronics,Femtech,14,200,11,2025/03/21
11,P011,Itel Phone,Electronics,Femtech,12,90,4,2025/03/28
12,P012,Tecno Headphone,Electronics,Femtech,15,25,2,2025/04/01
13,P013,Television,Electronics,Femtech,5,550,2,2025/04/08
14,P014,Remote,Electronics,Femtech,5,15,1,2025/04/21
15,P015,Oraimo Headphone,Electronics,Femtech,15,30,5,2025/04/28
16,P016,Samsung Laptop,Electronics,Jumia,5,1000,3,2025/05/01
17,P017,Bulb,Electrical,Femtech,25,5,2,2025/05/08
18,P018,Samsung Phone,Electronics,Jumia,13,1000,4,2025/05/15
19,P019,Hp Laptop,Electronics,Femtech,8,950,3,2025/05/21
20,P020,Dell Laptop,Electronics,Femtech,9,900,4,2025/05/28

In [22]:
df["Quantity"] = pd.to_numeric(df["Quantity"])

df["Quantity"]

C:\Users\ola-dev\AppData\Local\Temp\ipykernel_22652\3664233397.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Quantity"] = pd.to_numeric(df["Quantity"])

0     11
1     20
2     21
3      5
4     30
6      7
7     10
8     12
9     19
10    14
11    12
12    15
13     5
14     5
15    15
16     5
17    25
18    13
19     8
20     9
Name: Quantity, dtype: int64

In [23]:
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit price($),Reorder_Level,Last_Update
0,P001,Hp Laptop,Electronics,Jumia,11,1200,5,2025/01/01
1,P002,nan,Electronics,Femtech,20,500,12,2025/01/08
2,P003,Hp Keyboard,Electronics,Jumia,21,50,10,2025/01/22
3,P004,Infinix Phone,Electronics,Jumia,5,150,2,2025/01/30
4,P005,Iphone Headphone,Electronics,Femtech,30,100,20,2025/02/01
6,P006,Tecno Phone,Electronics,Jumia,7,120,2,2025/02/21
7,P007,Dell Laptop,Electronics,Femtech,10,800,3,2025/02/28
8,P008,Accer Laptop,Electronics,Femtech,12,750,4,2025/03/01
9,P009,Dell Keyboard,Electronics,Jumia,19,30,2,2025/03/08
10,P010,Tecno Tablet,Electronics,Femtech,14,200,11,2025/03/21
11,P011,Itel Phone,Electronics,Femtech,12,90,4,2025/03/28
12,P012,Tecno Headphone,Electronics,Femtech,15,25,2,2025/04/01
13,P013,Television,Electronics,Femtech,5,550,2,2025/04/08
14,P014,Remote,Electronics,Femtech,5,15,1,2025/04/21
15,P015,Oraimo Headphone,Electronics,Femtech,15,30,5,2025/04/28
16,P016,Samsung Laptop,Electronics,Jumia,5,1000,3,2025/05/01
17,P017,Bulb,Electrical,Femtech,25,5,2,2025/05/08
18,P018,Samsung Phone,Electronics,Jumia,13,1000,4,2025/05/15
19,P019,Hp Laptop,Electronics,Femtech,8,950,3,2025/05/21
20,P020,Dell Laptop,Electronics,Femtech,9,900,4,2025/05/28

In [24]:
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit price($),Reorder_Level,Last_Update
0,P001,Hp Laptop,Electronics,Jumia,11,1200,5,2025/01/01
1,P002,nan,Electronics,Femtech,20,500,12,2025/01/08
2,P003,Hp Keyboard,Electronics,Jumia,21,50,10,2025/01/22
3,P004,Infinix Phone,Electronics,Jumia,5,150,2,2025/01/30
4,P005,Iphone Headphone,Electronics,Femtech,30,100,20,2025/02/01
6,P006,Tecno Phone,Electronics,Jumia,7,120,2,2025/02/21
7,P007,Dell Laptop,Electronics,Femtech,10,800,3,2025/02/28
8,P008,Accer Laptop,Electronics,Femtech,12,750,4,2025/03/01
9,P009,Dell Keyboard,Electronics,Jumia,19,30,2,2025/03/08
10,P010,Tecno Tablet,Electronics,Femtech,14,200,11,2025/03/21
11,P011,Itel Phone,Electronics,Femtech,12,90,4,2025/03/28
12,P012,Tecno Headphone,Electronics,Femtech,15,25,2,2025/04/01
13,P013,Television,Electronics,Femtech,5,550,2,2025/04/08
14,P014,Remote,Electronics,Femtech,5,15,1,2025/04/21
15,P015,Oraimo Headphone,Electronics,Femtech,15,30,5,2025/04/28
16,P016,Samsung Laptop,Electronics,Jumia,5,1000,3,2025/05/01
17,P017,Bulb,Electrical,Femtech,25,5,2,2025/05/08
18,P018,Samsung Phone,Electronics,Jumia,13,1000,4,2025/05/15
19,P019,Hp Laptop,Electronics,Femtech,8,950,3,2025/05/21
20,P020,Dell Laptop,Electronics,Femtech,9,900,4,2025/05/28

In [25]:
#product that needs restocking
df[["Quantity", "Reorder_Level"]]

    Quantity  Reorder_Level
0         11              5
1         20             12
2         21             10
3          5              2
4         30             20
6          7              2
7         10              3
8         12              4
9         19              2
10        14             11
11        12              4
12        15              2
13         5              2
14         5              1
15        15              5
16         5              3
17        25              2
18        13              4
19         8              3
20         9              4

In [26]:
#which product needs restocking

df["Restock_Status"] = df.apply(
    lambda row: "Restock" if row["Quantity"] <= row["Reorder_Level"] else "YES",
    axis=1
)

df

C:\Users\ola-dev\AppData\Local\Temp\ipykernel_22652\3016380288.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Restock_Status"] = df.apply(

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit price($),Reorder_Level,Last_Update,Restock_Status
0,P001,Hp Laptop,Electronics,Jumia,11,1200,5,2025/01/01,YES
1,P002,nan,Electronics,Femtech,20,500,12,2025/01/08,YES
2,P003,Hp Keyboard,Electronics,Jumia,21,50,10,2025/01/22,YES
3,P004,Infinix Phone,Electronics,Jumia,5,150,2,2025/01/30,YES
4,P005,Iphone Headphone,Electronics,Femtech,30,100,20,2025/02/01,YES
6,P006,Tecno Phone,Electronics,Jumia,7,120,2,2025/02/21,YES
7,P007,Dell Laptop,Electronics,Femtech,10,800,3,2025/02/28,YES
8,P008,Accer Laptop,Electronics,Femtech,12,750,4,2025/03/01,YES
9,P009,Dell Keyboard,Electronics,Jumia,19,30,2,2025/03/08,YES
10,P010,Tecno Tablet,Electronics,Femtech,14,200,11,2025/03/21,YES
11,P011,Itel Phone,Electronics,Femtech,12,90,4,2025/03/28,YES
12,P012,Tecno Headphone,Electronics,Femtech,15,25,2,2025/04/01,YES
13,P013,Television,Electronics,Femtech,5,550,2,2025/04/08,YES
14,P014,Remote,Electronics,Femtech,5,15,1,2025/04/21,YES
15,P015,Oraimo Headphone,Electronics,Femtech,15,30,5,2025/04/28,YES
16,P016,Samsung Laptop,Electronics,Jumia,5,1000,3,2025/05/01,YES
17,P017,Bulb,Electrical,Femtech,25,5,2,2025/05/08,YES
18,P018,Samsung Phone,Electronics,Jumia,13,1000,4,2025/05/15,YES
19,P019,Hp Laptop,Electronics,Femtech,8,950,3,2025/05/21,YES
20,P020,Dell Laptop,Electronics,Femtech,9,900,4,2025/05/28,YES

In [27]:
#what is the average unit price per category

avg_units = df.groupby("Category")["Quantity"].mean()

avg_units

Category
Electrical     25.000000
Electronics    12.421053
Name: Quantity, dtype: float64

In [28]:
#what supplier provides the most product

supplier_count = df["Supplier"].value_counts()

supplier_count

Supplier
Femtech    13
Jumia       7
Name: count, dtype: int64

In [29]:
#Top 5 most expensive product

top_5_expensive = df.sort_values(by="Unit price($)", ascending=False).head(5)

top_5_expensive

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit price($),Reorder_Level,Last_Update,Restock_Status
0,P001,Hp Laptop,Electronics,Jumia,11,1200,5,2025/01/01,YES
18,P018,Samsung Phone,Electronics,Jumia,13,1000,4,2025/05/15,YES
16,P016,Samsung Laptop,Electronics,Jumia,5,1000,3,2025/05/01,YES
19,P019,Hp Laptop,Electronics,Femtech,8,950,3,2025/05/21,YES
20,P020,Dell Laptop,Electronics,Femtech,9,900,4,2025/05/28,YES